### ISSUE TITLE
Attributes aren't being updated anymore

### ISSUE THREAD

**Issue by woutf** [mrtnbr/ha_spaarnelanden_inzameling#3]
In the newest version of Home Assistant, the attributes of the container aren't being updated. For Paper/Pdb-containers, the attribute 'date_last_emptied' used to be available, but isn't anymore.
![image](https://user-images.githubusercontent.com/7326288/166895210-55e77998-5b92-4e31-9f80-26d9d9bde436.png)

**Comment by mrtnbr** [comment]
Newest version = 2022.5?

**Comment by woutf** [comment]
I think it actually started in 2022.3 or 2022.4

**Comment by mrtnbr** [comment]
Fixed in release 0.0.3 :)

Better late than never!

**Comment by woutf** [comment]
It's mostly fixed, although one attribute isn't working: date_last_emptied. It just sits at 1970-01-01T01:00:00.001000 even though in the source code of the website the value is correct.

**Comment by mrtnbr** [comment]
There were more changes on the spaarnelanden website, I have released v0.0.5
