### ISSUE TITLE
Is this component still working?

### ISSUE THREAD

**Issue by freakshock88** [mrtnbr/ha_spaarnelanden_inzameling#5]
Hi! 

I was glad to find this component since I dragged my trash to the underground trashcan for nothing again today ;) 

I tried to set it up by adding the repo to HACS and then manually entering my container number in sensor.py. However, no sensor seems to be created in HASS. The only thing I can find in the logs is the integration being loaded:

```
2024-04-08 23:10:50.505 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spaarnelanden_inzameling which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

Am I doing something wrong or is the integration broken?

**Comment by mrtnbr** [comment]
It still works for me :) Did you put 
`- platform: spaarnelanden_inzameling`
in your Home Assistan sensor.yaml file?

**Comment by freakshock88** [comment]
Ah that was it indeed. It works for me as well now :) 
Even though this requirement makes sense, it's not mentioned in you're README btw. 
Thanks for your response :)

**Comment by mrtnbr** [comment]
Yeah 2/3 years ago it was the standard way of configuring it, but now it isn't any more :) I have added it to the README.
